# Generated by Django 3.1.3 on 2020-11-29 06:24

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(max_length=50)),
                ('valortotal', models.FloatField()),
                ('valor_ival', models.FloatField()),
                ('valor_neto', models.FloatField()),
                ('estado', models.CharField(blank=True, choices=[('m', 'proceso'), ('o', 'no entregado'), ('a', 'entregado'), ('r', 'Reserved')], default='m', help_text='Disponibilidad del libro', max_length=1)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='provedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripción del producto', max_length=1000)),
                ('pedido', models.ManyToManyField(help_text='Seleccione un pedido', to='app3.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_provedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3.provedor'),
        ),
    ]
