# Generated by Django 3.1.3 on 2020-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
